# Generated by Django 2.2.3 on 2019-07-28 10:19

import App.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=App.models.file_upload)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('logo', models.ImageField(upload_to=App.models.file_upload)),
                ('cover', models.ImageField(upload_to=App.models.file_upload)),
                ('max_limit', models.IntegerField(default=0)),
                ('speed_limit', models.IntegerField(default=0)),
                ('road', models.CharField(max_length=300)),
                ('subscribers', models.ManyToManyField(blank=True, null=True, related_name='subscribers', to='App.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.TextField(blank=True, null=True)),
                ('direction', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='GpsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=250)),
                ('lng', models.CharField(max_length=250)),
                ('current_speed', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=250, null=True)),
                ('acceleration', models.CharField(blank=True, max_length=250, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.Competition')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='App.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='App.AppUser')),
            ],
        ),
    ]
