# Generated by Django 2.2.3 on 2019-09-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190728_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.Competition'),
            preserve_default=False,
        ),
    ]
