# Generated by Django 2.2.3 on 2019-09-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_competition_end_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_point',
            field=models.CharField(max_length=200),
        ),
    ]
