# Generated by Django 2.2.3 on 2019-09-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190910_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
