# Generated by Django 2.2.3 on 2019-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_trip_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
