# Generated by Django 2.2.3 on 2019-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190910_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpslog',
            name='road',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
