# Generated by Django 2.2.3 on 2019-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_trip_total_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='distance',
            new_name='distance_max_limit',
        ),
        migrations.AddField(
            model_name='competition',
            name='distance_minimum_limit',
            field=models.IntegerField(default=0),
        ),
    ]
